In [1]:
import numpy as np
import pandas as pd
gameWeekData = pd.read_csv('data/2016-17/players/Aaron_Cresswell/gw.csv')
historyData = pd.read_csv('data/2016-17/players/Aaron_Cresswell/history.csv')
print list(gameWeekData)
print
print list(historyData)
gameWeekData['total_points'].plot()

['assists', 'attempted_passes', 'big_chances_created', 'big_chances_missed', 'bonus', 'bps', 'clean_sheets', 'clearances_blocks_interceptions', 'completed_passes', 'creativity', 'dribbles', 'ea_index', 'element', 'errors_leading_to_goal', 'errors_leading_to_goal_attempt', 'fixture', 'fouls', 'goals_conceded', 'goals_scored', 'ict_index', 'id', 'influence', 'key_passes', 'kickoff_time', 'kickoff_time_formatted', 'loaned_in', 'loaned_out', 'minutes', 'offside', 'open_play_crosses', 'opponent_team', 'own_goals', 'penalties_conceded', 'penalties_missed', 'penalties_saved', 'recoveries', 'red_cards', 'round', 'saves', 'selected', 'tackled', 'tackles', 'target_missed', 'team_a_score', 'team_h_score', 'threat', 'total_points', 'transfers_balance', 'transfers_in', 'transfers_out', 'value', 'was_home', 'winning_goals', 'yellow_cards']

['assists', 'bonus', 'bps', 'clean_sheets', 'creativity', 'ea_index', 'element_code', 'end_cost', 'goals_conceded', 'goals_scored', 'ict_index', 'id', 'influence', 'minutes', 'own_goals', 'penalties_missed', 'penalties_saved', 'red_cards', 'saves', 'season', 'season_name', 'start_cost', 'threat', 'total_points', 'yellow_cards']

In [2]:
import glob
path = 'data/2016-17/players'
filenames = glob.glob(path + "/*/gw.csv")
all_p_gwData = (pd.read_csv(f) for f in filenames)
p_gwData = pd.concat(all_p_gwData, keys=[i for i in range(683)])
p_gwData[:50]

# not multidimensional, but multiindexed
# https://pandas.pydata.org/pandas-docs/stable/merging.html

      assists  attempted_passes  big_chances_created  big_chances_missed  \
0 0         0                 0                    0                   0
  1         0                 0                    0                   0
  2         0                 0                    0                   0
  3         0                 0                    0                   0
  4         0                 0                    0                   0
  5         0                 0                    0                   0
  6         0                 0                    0                   0
  7         1                20                    1                   0
  8         0                 0                    0                   0
  9         0                41                    0                   0
  10        0                30                    0                   0
  11        0                37                    0                   0
  12        0                24                    0                   0
  13        0                 0                    0                   0
  14        0                25                    0                   0
  15        0                39                    0                   0
  16        0                41                    0                   0
  17        0                39                    0                   0
  18        0                39                    0                   0
  19        0                34                    0                   0
  20        0                32                    0                   0
  21        0                33                    1                   0
  22        0                25                    0                   1
  23        0                25                    0                   0
  24        0                15                    0                   0
  25        0                21                    1                   0
  26        0                58                    0                   0
  27        0                28                    0                   0
  28        0                29                    0                   0
  29        1                28                    1                   0
  30        0                 0                    0                   0
  31        0                 0                    0                   0
  32        0                 0                    0                   0
  33        0                 5                    0                   0
  34        0                 7                    0                   0
  35        0                20                    0                   0
  36        0                30                    0                   0
  37        0                30                    0                   0
1 0         0                 3                    0                   0
  1         0                 0                    0                   0
  2         0                 0                    0                   0
  3         0                 0                    0                   0
  4         0                 0                    0                   0
  5         0                 0                    0                   0
  6         0                 0                    0                   0
  7         0                 0                    0                   0
  8         0                 0                    0                   0
  9         0                 2                    0                   0
  10        0                11                    0                   0
  11        0                19                    0                   0

      bonus  bps  clean_sheets  clearances_blocks_interceptions  \
0 0       0    0             0                                0
  1       0    0             0                                0
  2       0    0             0                                0
  3       0    0             0                                0
  4       0    0             0                                0
  5       0    0             0                                0
  6       0    0             0                                0
  7       0   23             1                                4
  8       0    0             0                                0
  9       0   12             0                                1
  10      0   13             0                                4
  11      0   13             0                                2
  12      0    7             0                                4
  13      0    0             0                                0
  14      0   12             0                               16
  15      0   17             1                                3
  16      1   27             1                                8
  17      0   12             0                                6
  18      0   24             0                                1
  19      0   10             0                                1
  20      0   20             1                                2
  21      0   17             0                                5
  22      0    4             0                                4
  23      0    5             0                                5
  24      0    3             0                                0
  25      0   10             0                                1
  26      0   16             0                                3
  27      0   13             0                                2
  28      0    8             0                                3
  29      0   16             0                                0
  30      0    0             0                                0
  31      0    0             0                                0
  32      0    0             0                                0
  33      0    3             0                                0
  34      0    9             0                                6
  35      0   20             1                                4
  36      0   13             0                                2
  37      0    7             0                                2
1 0       0    6             0                                1
  1       0    0             0                                0
  2       0    0             0                                0
  3       0    0             0                                0
  4       0    0             0                                0
  5       0    0             0                                0
  6       0    0             0                                0
  7       0    0             0                                0
  8       0    0             0                                0
  9       0    6             0                                0
  10      0    6             0                                2
  11      0    6             0                                0

      completed_passes  creativity      ...       team_h_score  threat  \
0 0                  0         0.0      ...                  2     0.0
  1                  0         0.0      ...                  1     0.0
  2                  0         0.0      ...                  3     0.0
  3                  0         0.0      ...                  2     0.0
  4                  0         0.0      ...                  4     0.0
  5                  0         0.0      ...                  0     0.0
  6                  0         0.0      ...                  1     0.0
  7                 12        25.1      ...                  0     6.0
  8                  0         0.0      ...                  1     0.0
  9                 35         7.9      ...                  2     0.0
  10                23         1.9      ...                  1     4.0
  11                29         2.8      ...                  3     2.0
  12                16         1.7      ...                  1     6.0
  13                 0         0.0      ...                  1     0.0
  14                18         5.7      ...                  2     1.0
  15                27         7.2      ...                  1    18.0
  16                33         1.8      ...                  1     8.0
  17                30        11.7      ...                  1     0.0
  18                36        57.8      ...                  1    15.0
  19                31         1.9      ...                  0     0.0
  20                23        12.0      ...                  3     0.0
  21                25        26.8      ...                  1     6.0
  22                15         5.0      ...                  0     4.0
  23                19         6.1      ...                  1    17.0
  24                12         0.9      ...                  2     0.0
  25                15        15.5      ...                  1     3.0
  26                47         3.8      ...                  1    18.0
  27                20        11.5      ...                  3     2.0
  28                21        15.4      ...                  2     0.0
  29                16        14.6      ...                  2     0.0
  30                 0         0.0      ...                  3     0.0
  31                 0         0.0      ...                  1     0.0
  32                 0         0.0      ...                  2     0.0
  33                 1         0.3      ...                  0     0.0
  34                 6        14.3      ...                  0     0.0
  35                14         5.3      ...                  1     4.0
  36                24         1.5      ...                  0     0.0
  37                21        26.2      ...                  1     7.0
1 0                  2         0.3      ...                  1     0.0
  1                  0         0.0      ...                  1     0.0
  2                  0         0.0      ...                  1     0.0
  3                  0         0.0      ...                  0     0.0
  4                  0         0.0      ...                  3     0.0
  5                  0         0.0      ...                  1     0.0
  6                  0         0.0      ...                  1     0.0
  7                  0         0.0      ...                  1     0.0
  8                  0         0.0      ...                  2     0.0
  9                  2         0.3      ...                  2     0.0
  10                11         1.6      ...                  5     0.0
  11                13         3.2      ...                  1     4.0

      total_points  transfers_balance  transfers_in  transfers_out  value  \
0 0              0                  0             0              0     55
  1              0              -3002            79           3081     55
  2              0              -2053            28           2081     54
  3              0              -1221            45           1266     54
  4              0               -520            29            549     54
  5              0               -500            20            520     54
  6              0               -285            40            325     53
  7              6                468           678            210     53
  8              0               1813          2313            500     53
  9              1               2432          2697            265     53
  10             2               2112          2564            452     53
  11             1                839          1671            832     53
  12             1               -204           503            707     53
  13             0              -1707           346           2053     53
  14             1              -1195           163           1358     53
  15             6               2619          2875            256     53
  16             7               3143          3422            279     53
  17             2               -104          1033           1137     53
  18             2               -517           499           1016     53
  19             1               -979           656           1635     53
  20             6               -232          1768           2000     53
  21             2                164          1157            993     53
  22             0               -772           511           1283     53
  23             1               -649           368           1017     53
  24             1               -553           817           1370     52
  25             2               -556           435            991     52
  26             1               -221           390            611     52
  27             1               7409          7910            501     52
  28             1              -1475           437           1912     52
  29             5               -473           559           1032     52
  30             0              -2305            94           2399     52
  31             0              -3029            76           3105     52
  32             0              -1477            90           1567     51
  33             1               -619            94            713     51
  34             1               -201            88            289     51
  35             6               -396            43            439     51
  36             0               -198           182            380     51
  37             2                290           446            156     51
1 0              1                  0             0              0     60
  1              0              -1699           290           1989     60
  2              0              -2231           284           2515     59
  3              0              -1764           216           1980     58
  4              0               -995           131           1126     58
  5              0              -1108           110           1218     57
  6              0               -539            73            612     57
  7              0               -581            65            646     56
  8              0               -401            28            429     56
  9              1               -173            36            209     56
  10             1               -171            50            221     56
  11             2               -130            60            190     56

      was_home  winning_goals  yellow_cards
0 0      False              0             0
  1       True              0             0
  2      False              0             0
  3       True              0             0
  4      False              0             0
  5       True              0             0
  6       True              0             0
  7      False              0             0
  8       True              0             0
  9      False              0             0
  10      True              0             0
  11     False              0             0
  12     False              0             1
  13      True              0             0
  14     False              0             0
  15      True              0             0
  16      True              0             0
  17     False              0             0
  18     False              0             0
  19      True              0             0
  20      True              0             0
  21     False              0             0
  22      True              0             0
  23     False              0             1
  24      True              0             0
  25     False              0             0
  26      True              0             0
  27     False              0             0
  28      True              0             0
  29     False              0             0
  30     False              0             0
  31      True              0             0
  32     False              0             0
  33      True              0             0
  34     False              0             0
  35      True              0             0
  36      True              0             0
  37     False              0             0
1 0       True              0             0
  1      False              0             0
  2       True              0             0
  3      False              0             0
  4       True              0             0
  5      False              0             0
  6       True              0             0
  7      False              0             0
  8      False              0             0
  9       True              0             0
  10     False              0             0
  11      True              0             0

[50 rows x 54 columns]

In [14]:
path = 'data/2016-17/players'
filenames = glob.glob(path + "/*/history.csv")
all_p_hData = (pd.read_csv(f).mean() for f in filenames)
p_hData = pd.concat(all_p_hData, keys=[i for i in range(683)])
print p_hData

0    assists                 3.333333
     bonus                   8.666667
     bps                   527.333333
     clean_sheets            8.333333
     creativity             94.900000
     ea_index              341.333333
     element_code        55459.000000
     end_cost               55.000000
     goals_conceded         44.000000
     goals_scored            1.333333
     ict_index              23.733333
     id                   6328.666667
     influence             102.533333
     minutes              2949.666667
     own_goals               0.000000
     penalties_missed        0.000000
     penalties_saved         0.000000
     red_cards               0.333333
     saves                   0.000000
     season                 10.000000
     start_cost             55.000000
     threat                 40.333333
     total_points          107.333333
     yellow_cards            2.666667
1    assists                 5.363636
     bonus                   7.454545
     bps                    66.363636
     clean_sheets            4.181818
     creativity              8.490909
     ea_index              150.000000
                             ...
681  saves                   0.000000
     season                  4.200000
     start_cost             60.000000
     threat                  0.600000
     total_points           50.800000
     yellow_cards            3.200000
682  assists                 3.333333
     bonus                   9.000000
     bps                   187.000000
     clean_sheets            6.000000
     creativity            151.633333
     ea_index              147.000000
     element_code        42892.000000
     end_cost               80.000000
     goals_conceded         21.333333
     goals_scored            6.000000
     ict_index              69.033333
     id                   6270.000000
     influence             180.800000
     minutes              1531.333333
     own_goals               0.000000
     penalties_missed        0.000000
     penalties_saved         0.000000
     red_cards               0.000000
     saves                   0.000000
     season                  9.333333
     start_cost             83.333333
     threat                359.333333
     total_points           79.666667
     yellow_cards            2.000000
Length: 16392, dtype: float64

In [55]:
mat = np.zeros((683,9))
for i in range(683):
    mat[i][0] = p_hData[i]['assists']
    mat[i][1] = p_hData[i]['goals_scored']
    mat[i][2] = p_hData[i]['bonus']
    mat[i][3] = p_hData[i]['clean_sheets']
    mat[i][4] = p_hData[i]['creativity']
    mat[i][5] = p_hData[i]['saves']
    mat[i][6] = p_hData[i]['influence']
    mat[i][7] = p_hData[i]['start_cost']
    mat[i][8] = 0 if p_hData[i]['minutes'] == 0 else p_hData[i]['total_points'] / p_hData[i]['minutes']

In [56]:
from sklearn import linear_model
regr = linear_model.LinearRegression(normalize=True)
regr.fit(mat[:,0:7], mat[:,8])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=True)

In [57]:
print regr.coef_
print regr.intercept_

[  1.86498515e-03   1.84792236e-03   1.90717954e-04  -2.31108928e-03
  -4.91922858e-06   5.62941097e-05  -2.76038775e-06]
0.0483264326558

In [76]:
player_id = pd.read_csv('data/2016-17/player_idlist.csv')
player_pos = pd.read_csv('data/16-17 pos clean.csv')

In [25]:
player_id[:5]

        first_name  second_name  id
0            David       Ospina   1
1             Petr         Cech   2
2          Laurent    Koscielny   3
3              Per  Mertesacker   4
4  Gabriel Armando     de Abreu   5

In [15]:
player_pos[:5]

              player    position  Unnamed: 2  Unnamed: 3  Unnamed: 4
0         Almen Abdi  Midfielder         NaN         NaN         NaN
1      Tammy Abraham     Forward         NaN         NaN         NaN
2       Charlie Adam  Midfielder         NaN         NaN         NaN
3         Adam Smith    Defender         NaN         NaN         NaN
4  Emmanuel Adebayor     Forward         NaN         NaN         NaN

In [30]:
fname = player_id['first_name'][0]
sname = player_id['second_name'][0]
pname = fname + ' ' + sname
print pname

David Ospina

In [33]:
pname2 = player_pos['player'][0]
print pname2

Almen Abdi

In [77]:
n = 0
m = 0
for i in player_id.index:
    fname = player_id['first_name'][i]
    sname = player_id['second_name'][i]
    pname = fname + ' ' + sname
    n += 1
    for j in player_pos.index:
        if player_pos['player'][j] == pname:
#             print pname, player_pos['position'][j]
            m += 1
            player_id.loc[i, 'position'] = player_pos['position'][j]
# print n, m

In [78]:
player_id

          first_name         second_name   id    position
0              David              Ospina    1  Goalkeeper
1               Petr                Cech    2  Goalkeeper
2            Laurent           Koscielny    3    Defender
3                Per         Mertesacker    4    Defender
4    Gabriel Armando            de Abreu    5         NaN
5             Héctor            Bellerín    6         NaN
6             Kieran               Gibbs    7    Defender
7            Mathieu             Debuchy    8    Defender
8               Carl           Jenkinson    9    Defender
9              Nacho             Monreal   10    Defender
10             Calum            Chambers   11    Defender
11            Alexis             Sánchez   12         NaN
12              Theo             Walcott   13     Forward
13             Mesut                Özil   14         NaN
14          Santiago             Cazorla   15  Midfielder
15             Aaron              Ramsey   16  Midfielder
16              Jack            Wilshere   17  Midfielder
17              Alex  Oxlade-Chamberlain   18  Midfielder
18             Serge              Gnabry   19     Forward
19           Francis            Coquelin   20  Midfielder
20              Alex               Iwobi   21  Midfielder
21           Mohamed              Elneny   22  Midfielder
22              Joel            Campbell   23     Forward
23            Granit               Xhaka   24  Midfielder
24           Olivier              Giroud   25     Forward
25             Danny             Welbeck   26     Forward
26              Yaya              Sanogo   27     Forward
27            Takuma               Asano   28         NaN
28             Artur               Boruc   29  Goalkeeper
29              Adam            Federici   30  Goalkeeper
..               ...                 ...  ...         ...
653           Connor             Roberts  654         NaN
654          Matthew             Willock  655         NaN
655             Axel            Tuanzebe  656    Defender
656  Damian Emiliano            Martinez  657         NaN
657              Joe            Williams  658  Midfielder
658             Dion             Pereira  659  Midfielder
659             Matt               Macey  660  Goalkeeper
660            James             Husband  661    Defender
661       Joel Dinis      Castro Pereira  662         NaN
662          Eduardo   Dos Reis Carvalho  663         NaN
663            Moses              Makasi  664  Midfielder
664           Nathan             Holland  665         NaN
665            Rhian            Brewster  666         NaN
666            Scott           McTominay  667         NaN
667            Angus                Gunn  668  Goalkeeper
668          Demetri            Mitchell  669         NaN
669          Elliott               Moore  670         NaN
670            Filip             Lesniak  671         NaN
671           Samuel            Shashoua  672         NaN
672          Zachary            Dearnley  673         NaN
673           Joshua              Harrop  674         NaN
674           Daniel                Kemp  675  Midfielder
675           Daniel               Batty  676         NaN
676            Aaron            Ramsdale  677         NaN
677          Matthew         Worthington  678         NaN
678              Sam            Surridge  679     Forward
679            Angel               Gomes  680         NaN
680           Kieran              O'Hara  681         NaN
681          Gerhard             Tremmel  682         NaN
682             Rene           Gilmartin  683  Goalkeeper

[683 rows x 4 columns]

In [80]:
player_id.to_csv('player_position.csv')

In [2]:
import pandas as pd

schedule_16_17 = pd.read_csv('data/UK_Football_Fixtures_2016-17.csv', usecols=['HOME TEAM', 'AWAY TEAM'])
schedule_16_17['GAMEWEEK'] = [i / 10 + 1 for i in range(schedule_16_17.shape[0])]
schedule_16_17.set_index('GAMEWEEK', drop=True, inplace=True)

schedule_17_18 = pd.read_csv('data/UK_Football_Fixtures_2017-18.csv', usecols=['HOME TEAM', 'AWAY TEAM'])
schedule_17_18['GAMEWEEK'] = [i / 10 + 1 for i in range(schedule_17_18.shape[0])]
schedule_17_18.set_index('GAMEWEEK', drop=True, inplace=True)

In [4]:
a = pd.read_csv('data/2016-17/players/Aaron_Cresswell/gw.csv')

In [10]:
b = a['team_h_score'] - a['team_a_score']
for i in a.index:
    if a.loc[i, 'was_home'] == True:
        if b[i] < 0:
            a.loc[i, 'match_result'] = -1
        elif b[i] == 0:
            a.loc[i, 'match_result'] = 0
        else:
            a.loc[i, 'match_result'] = 1
    else:
        if b[i] < 0:
            a.loc[i, 'match_result'] = 1
        elif b[i] == 0:
            a.loc[i, 'match_result'] = 0
        else:
            a.loc[i, 'match_result'] = -1

In [11]:
a

,assists,attempted_passes,big_chances_created,big_chances_missed,bonus,bps,clean_sheets,clearances_blocks_interceptions,completed_passes,creativity,...,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,winning_goals,yellow_cards,match_result
0,0,0,0,0,0,0,0,0,0,0.0,...,0.0,0,0,0,0,55,False,0,0,NaN
1,0,0,0,0,0,0,0,0,0,0.0,...,0.0,0,-3002,79,3081,55,True,0,0,-1.0
2,0,0,0,0,0,0,0,0,0,0.0,...,0.0,0,-2053,28,2081,54,False,0,0,NaN
3,0,0,0,0,0,0,0,0,0,0.0,...,0.0,0,-1221,45,1266,54,True,0,0,1.0
4,0,0,0,0,0,0,0,0,0,0.0,...,0.0,0,-520,29,549,54,False,0,0,NaN
5,0,0,0,0,0,0,0,0,0,0.0,...,0.0,0,-500,20,520,54,True,0,0,1.0
6,0,0,0,0,0,0,0,0,0,0.0,...,0.0,0,-285,40,325,53,True,0,0,0.0
7,1,20,1,0,0,23,1,4,12,25.1,...,6.0,6,468,678,210,53,False,0,0,NaN
8,0,0,0,0,0,0,0,0,0,0.0,...,0.0,0,1813,2313,500,53,True,0,0,-1.0
9,0,41,0,0,0,12,0,1,35,7.9,...,0.0,1,2432,2697,265,53,False,0,0,NaN
10,0,30,0,0,0,13,0,4,23,1.9,...,4.0,2,2112,2564,452,53,True,0,0,0.0
11,0,37,0,0,0,13,0,2,29,2.8,...,2.0,1,839,1671,832,53,False,0,0,NaN
12,0,24,0,0,0,7,0,4,16,1.7,...,6.0,1,-204,503,707,53,False,0,1,NaN
13,0,0,0,0,0,0,0,0,0,0.0,...,0.0,0,-1707,346,2053,53,True,0,0,1.0
14,0,25,0,0,0,12,0,16,18,5.7,...,1.0,1,-1195,163,1358,53,False,0,0,NaN
15,0,39,0,0,0,17,1,3,27,7.2,...,18.0,6,2619,2875,256,53,True,0,0,-1.0
16,0,41,0,0,1,27,1,8,33,1.8,...,8.0,7,3143,3422,279,53,True,0,0,-1.0
17,0,39,0,0,0,12,0,6,30,11.7,...,0.0,2,-104,1033,1137,53,False,0,0,NaN
18,0,39,0,0,0,24,0,1,36,57.8,...,15.0,2,-517,499,1016,53,False,0,0,NaN
19,0,34,0,0,0,10,0,1,31,1.9,...,0.0,1,-979,656,1635,53,True,0,0,1.0
20,0,32,0,0,0,20,1,2,23,12.0,...,0.0,6,-232,1768,2000,53,True,0,0,-1.0
21,0,33,1,0,0,17,0,5,25,26.8,...,6.0,2,164,1157,993,53,False,0,0,NaN
22,0,25,0,1,0,4,0,4,15,5.0,...,4.0,0,-772,511,1283,53,True,0,0,1.0
23,0,25,0,0,0,5,0,5,19,6.1,...,17.0,1,-649,368,1017,53,False,0,1,NaN
24,0,15,0,0,0,3,0,0,12,0.9,...,0.0,1,-553,817,1370,52,True,0,0,0.0
25,0,21,1,0,0,10,0,1,15,15.5,...,3.0,2,-556,435,991,52,False,0,0,NaN
26,0,58,0,0,0,16,0,3,47,3.8,...,18.0,1,-221,390,611,52,True,0,0,1.0
27,0,28,0,0,0,13,0,2,20,11.5,...,2.0,1,7409,7910,501,52,False,0,0,NaN
28,0,29,0,0,0,8,0,3,21,15.4,...,0.0,1,-1475,437,1912,52,True,0,0,1.0
29,1,28,1,0,0,16,0,0,16,14.6,...,0.0,5,-473,559,1032,52,False,0,0,NaN
30,0,0,0,0,0,0,0,0,0,0.0,...,0.0,0,-2305,94,2399,52,False,0,0,NaN
31,0,0,0,0,0,0,0,0,0,0.0,...,0.0,0,-3029,76,3105,52,True,0,0,-1.0
32,0,0,0,0,0,0,0,0,0,0.0,...,0.0,0,-1477,90,1567,51,False,0,0,NaN
33,0,5,0,0,0,3,0,0,1,0.3,...,0.0,1,-619,94,713,51,True,0,0,0.0
34,0,7,0,0,0,9,0,6,6,14.3,...,0.0,1,-201,88,289,51,False,0,0,NaN
35,0,20,0,0,0,20,1,4,14,5.3,...,4.0,6,-396,43,439,51,True,0,0,-1.0
36,0,30,0,0,0,13,0,2,24,1.5,...,0.0,0,-198,182,380,51,True,0,0,1.0
37,0,30,0,0,0,7,0,2,21,26.2,...,7.0,2,290,446,156,51,False,0,0,NaN