In [1]:
import numpy as np
import pandas as pd
gameWeekData = pd.read_csv('data/2016-17/players/Aaron_Cresswell/gw.csv')
historyData = pd.read_csv('data/2016-17/players/Aaron_Cresswell/history.csv')
print list(gameWeekData)
print
print list(historyData)
gameWeekData['total_points'].plot()

['assists', 'attempted_passes', 'big_chances_created', 'big_chances_missed', 'bonus', 'bps', 'clean_sheets', 'clearances_blocks_interceptions', 'completed_passes', 'creativity', 'dribbles', 'ea_index', 'element', 'errors_leading_to_goal', 'errors_leading_to_goal_attempt', 'fixture', 'fouls', 'goals_conceded', 'goals_scored', 'ict_index', 'id', 'influence', 'key_passes', 'kickoff_time', 'kickoff_time_formatted', 'loaned_in', 'loaned_out', 'minutes', 'offside', 'open_play_crosses', 'opponent_team', 'own_goals', 'penalties_conceded', 'penalties_missed', 'penalties_saved', 'recoveries', 'red_cards', 'round', 'saves', 'selected', 'tackled', 'tackles', 'target_missed', 'team_a_score', 'team_h_score', 'threat', 'total_points', 'transfers_balance', 'transfers_in', 'transfers_out', 'value', 'was_home', 'winning_goals', 'yellow_cards']

['assists', 'bonus', 'bps', 'clean_sheets', 'creativity', 'ea_index', 'element_code', 'end_cost', 'goals_conceded', 'goals_scored', 'ict_index', 'id', 'influence', 'minutes', 'own_goals', 'penalties_missed', 'penalties_saved', 'red_cards', 'saves', 'season', 'season_name', 'start_cost', 'threat', 'total_points', 'yellow_cards']

In [2]:
import glob
path = 'data/2016-17/players'
filenames = glob.glob(path + "/*/gw.csv")
all_p_gwData = (pd.read_csv(f) for f in filenames)
p_gwData = pd.concat(all_p_gwData, keys=[i for i in range(683)])
p_gwData[:50]

# not multidimensional, but multiindexed
# https://pandas.pydata.org/pandas-docs/stable/merging.html

      assists  attempted_passes  big_chances_created  big_chances_missed  \
0 0         0                 7                    0                   0
  1         0                30                    0                   0
  2         0                24                    0                   0
  3         0                31                    0                   0
  4         0                23                    0                   0
  5         0                36                    0                   0
  6         0                16                    0                   0
  7         0                21                    0                   0
  8         0                47                    0                   1
  9         0                14                    0                   0
  10        0                35                    0                   0
  11        0                19                    0                   0
  12        0                33                    0                   0
  13        0                43                    0                   0
  14        0                39                    0                   0
  15        0                 0                    0                   0
  16        0                39                    0                   0
  17        0                37                    0                   0
  18        0                15                    0                   0
  19        0                46                    0                   0
  20        0                 2                    0                   0
  21        0                 0                    0                   0
  22        0                 0                    0                   0
  23        0                22                    0                   0
  24        0                35                    0                   0
  25        0                45                    0                   0
  26        0                33                    0                   0
  27        1                30                    0                   0
  28        0                37                    0                   0
  29        0                26                    0                   0
  30        0                38                    0                   0
  31        0                26                    0                   0
  32        0                52                    0                   0
  33        0                47                    0                   0
  34        0                49                    0                   0
1 0         0                 0                    0                   0
  1         0                 0                    0                   0
  2         0                 0                    0                   0
  3         0                17                    0                   0
  4         0                 9                    0                   0
  5         0                 0                    0                   0
  6         0                 5                    0                   0
  7         0                36                    0                   0
  8         1                32                    1                   0
  9         0                 0                    0                   0
  10        0                 0                    0                   0
  11        0                 0                    0                   0
  12        0                15                    0                   0
  13        0                24                    1                   0
  14        0                 0                    0                   0

      bonus  bps  clean_sheets  clearances_blocks_interceptions  \
0 0       0    3             0                                1
  1       0   12             0                                5
  2       0   24             1                                2
  3       0    9             0                                3
  4       0    5             0                                2
  5       0    5             0                                8
  6       0    3             1                                4
  7       0    9             0                                1
  8       0    3             0                                2
  9       0    1             0                                4
  10      0    6             0                                3
  11      1   28             0                                6
  12      0    7             0                                1
  13      0   12             0                                4
  14      0    3             1                                2
  15      0    0             0                                0
  16      0    9             0                                2
  17      0    5             1                                2
  18      0    4             0                                1
  19      0   13             1                                2
  20      0   -7             0                                0
  21      0    0             0                                0
  22      0    0             0                                0
  23      0    6             0                                4
  24      0   14             0                                5
  25      0    5             1                                0
  26      0    9             0                                3
  27      0   21             1                                2
  28      0    7             1                                3
  29      0    9             0                                6
  30      0   15             0                                0
  31      0   10             1                                4
  32      0   15             0                                3
  33      0   14             0                                5
  34      0    7             0                                1
1 0       0    0             0                                0
  1       0    0             0                                0
  2       0    0             0                                0
  3       0    0             0                                0
  4       0    7             0                                0
  5       0    0             0                                0
  6       0    4             0                                0
  7       0   17             0                                1
  8       2   24             0                                3
  9       0    0             0                                0
  10      0    0             0                                0
  11      0    0             0                                0
  12      0    3             0                                0
  13      0   15             0                                1
  14      0    0             0                                0

      completed_passes  creativity      ...       team_h_score  threat  \
0 0                  6         1.5      ...                  1     0.0
  1                 23        12.7      ...                  3     1.0
  2                 18         2.2      ...                  2    25.0
  3                 24        21.3      ...                  0    11.0
  4                 19         2.7      ...                  3     3.0
  5                 28         1.7      ...                  2     2.0
  6                 12         2.0      ...                  0     2.0
  7                 19         1.2      ...                  3    35.0
  8                 45        16.5      ...                  4     7.0
  9                 11         2.2      ...                  1    22.0
  10                25        18.1      ...                  2    39.0
  11                10        12.3      ...                  3     9.0
  12                29         5.7      ...                  1     9.0
  13                29         2.9      ...                  2     0.0
  14                24        14.5      ...                  1     4.0
  15                 0         0.0      ...                  4     0.0
  16                33         4.1      ...                  2     1.0
  17                25        12.2      ...                  1     3.0
  18                12         0.8      ...                  2     1.0
  19                38        16.3      ...                  1    33.0
  20                 0         0.0      ...                  2     0.0
  21                 0         0.0      ...                  1     0.0
  22                 0         0.0      ...                  1     0.0
  23                20         5.6      ...                  3     7.0
  24                27        11.4      ...                  2     0.0
  25                38         3.3      ...                  0     2.0
  26                23        15.8      ...                  0     0.0
  27                23        17.7      ...                  1     9.0
  28                27         2.5      ...                  0     0.0
  29                19         1.7      ...                  3     0.0
  30                33        12.9      ...                  0     2.0
  31                17         3.1      ...                  0     0.0
  32                43         3.4      ...                  2     8.0
  33                36         2.8      ...                  2    16.0
  34                39         3.3      ...                  1     8.0
1 0                  0         0.0      ...                  2     0.0
  1                  0         0.0      ...                  1     0.0
  2                  0         0.0      ...                  3     0.0
  3                 12        14.3      ...                  1     8.0
  4                  8         0.9      ...                  4     3.0
  5                  0         0.0      ...                  1     0.0
  6                  4         0.6      ...                  2     0.0
  7                 32        21.8      ...                  1    27.0
  8                 25        24.6      ...                  1    16.0
  9                  0         0.0      ...                  0     0.0
  10                 0         0.0      ...                  1     0.0
  11                 0         0.0      ...                  1     0.0
  12                13        12.3      ...                  1     5.0
  13                17        22.0      ...                  1     2.0
  14                 0         0.0      ...                  4     0.0

      total_points  transfers_balance  transfers_in  transfers_out  value  \
0 0              1               1286          1488            202     55
  1              2                -73           127            200     55
  2              8               -145            99            244     54
  3              2                472           595            123     54
  4              2                241           393            152     54
  5              1                -66           169            235     54
  6              3               -143            79            222     54
  7              2                -97           103            200     54
  8              2                -98            64            162     54
  9              2               -126            49            175     54
  10             1                -23            83            106     54
  11             8                -55            65            120     54
  12             1                565           628             63     54
  13             2                293           446            153     54
  14             2                645           853            208     54
  15             0               -687           127            814     54
  16             1               -169           124            293     54
  17             3                113           477            364     54
  18             2               -136           153            289     54
  19             3                  8           205            197     54
  20            -2                -30           117            147     54
  21             0               -586            27            613     53
  22             0               -249            13            262     53
  23             2                  8            62             54     53
  24             2                 52            84             32     53
  25             3                  8            48             40     53
  26             2                 -4            35             39     53
  27             6                 32            51             19     53
  28             3                163           204             41     53
  29             2                 -7            71             78     53
  30             1                -25            64             89     53
  31             3                 -9            53             62     53
  32             2                 41           110             69     53
  33             2                -37            42             79     53
  34             2                 64           121             57     53
1 0              0                  0             0              0     80
  1              0              -8991           328           9319     80
  2              0              -6709           125           6834     79
  3              1              -1301           935           2236     78
  4              1                284          1194            910     78
  5              0              -1331           546           1877     78
  6              1              -1235           145           1380     77
  7              2               -526           224            750     77
  8              7               -133           289            422     76
  9              0               1273          1623            350     76
  10             0               -965           465           1430     76
  11             0               -649           195            844     76
  12             1               -410            41            451     76
  13             2               -171           104            275     75
  14             0                278           505            227     75

      was_home  winning_goals  yellow_cards
0 0       True              0             0
  1      False              0             0
  2       True              1             0
  3       True              0             0
  4      False              0             0
  5       True              0             1
  6      False              0             0
  7       True              0             0
  8      False              0             0
  9       True              0             0
  10     False              0             1
  11      True              0             0
  12     False              0             1
  13     False              0             0
  14      True              0             1
  15      True              0             0
  16     False              0             1
  17      True              0             0
  18     False              0             0
  19      True              0             0
  20     False              0             0
  21      True              0             0
  22     False              0             0
  23     False              0             0
  24     False              0             0
  25     False              0             0
  26      True              0             0
  27      True              0             0
  28     False              0             0
  29     False              0             0
  30      True              0             1
  31     False              0             0
  32      True              0             0
  33     False              0             0
  34      True              0             0
1 0       True              0             0
  1      False              0             0
  2       True              0             0
  3      False              0             0
  4       True              0             0
  5      False              0             0
  6      False              0             0
  7       True              0             0
  8       True              0             0
  9      False              0             0
  10      True              0             0
  11     False              0             0
  12     False              0             0
  13      True              0             0
  14     False              0             0

[50 rows x 54 columns]

In [3]:
path = 'data/2016-17/players'
filenames = glob.glob(path + "/*/history.csv")
all_p_hData = (pd.read_csv(f).mean() for f in filenames)
p_hData = pd.concat(all_p_hData, keys=[i for i in range(683)])
print p_hData

0    assists                  1.000000
     bonus                    1.000000
     bps                    286.000000
     clean_sheets             9.000000
     creativity             234.400000
     ea_index                 0.000000
     element_code         83314.000000
     end_cost                53.000000
     goals_conceded          47.000000
     goals_scored             2.000000
     ict_index               77.400000
     id                    7340.000000
     influence              284.600000
     minutes               2691.000000
     own_goals                0.000000
     penalties_missed         0.000000
     penalties_saved          0.000000
     red_cards                1.000000
     saves                    0.000000
     season                  11.000000
     start_cost              55.000000
     threat                 259.000000
     total_points            76.000000
     yellow_cards             6.000000
1    assists                  7.000000
     bonus                    8.000000
     bps                    343.000000
     clean_sheets             9.000000
     creativity             505.100000
     ea_index                 0.000000
                             ...
681  saves                    0.000000
     season                  10.000000
     start_cost              56.666667
     threat                   0.000000
     total_points            54.333333
     yellow_cards             3.666667
682  assists                  0.000000
     bonus                    0.000000
     bps                      0.000000
     clean_sheets             0.000000
     creativity               0.000000
     ea_index                 0.000000
     element_code        168717.000000
     end_cost                40.000000
     goals_conceded           0.000000
     goals_scored             0.000000
     ict_index                0.000000
     id                    6867.000000
     influence                0.000000
     minutes                  0.000000
     own_goals                0.000000
     penalties_missed         0.000000
     penalties_saved          0.000000
     red_cards                0.000000
     saves                    0.000000
     season                  11.000000
     start_cost              40.000000
     threat                   0.000000
     total_points             0.000000
     yellow_cards             0.000000
Length: 16392, dtype: float64

In [4]:
mat = np.zeros((683,9))
for i in range(683):
    mat[i][0] = p_hData[i]['assists']
    mat[i][1] = p_hData[i]['goals_scored']
    mat[i][2] = p_hData[i]['bonus']
    mat[i][3] = p_hData[i]['clean_sheets']
    mat[i][4] = p_hData[i]['creativity']
    mat[i][5] = p_hData[i]['saves']
    mat[i][6] = p_hData[i]['influence']
    mat[i][7] = p_hData[i]['start_cost']
    mat[i][8] = 0 if p_hData[i]['minutes'] == 0 else p_hData[i]['total_points'] / p_hData[i]['minutes']

In [5]:
from sklearn import linear_model
regr = linear_model.LinearRegression(normalize=True)
regr.fit(mat[:,0:7], mat[:,8])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=True)

In [6]:
print regr.coef_
print regr.intercept_

[ 1.86498515e-03  1.84792236e-03  1.90717954e-04 -2.31108928e-03
 -4.91922858e-06  5.62941097e-05 -2.76038775e-06]
0.04832643265578758

In [8]:
player_id = pd.read_csv('data/2016-17/player_idlist.csv')
player_pos = pd.read_csv('data/2016-17 pos clean.csv')

In [9]:
player_id[:5]

        first_name  second_name  id
0            David       Ospina   1
1             Petr         Cech   2
2          Laurent    Koscielny   3
3              Per  Mertesacker   4
4  Gabriel Armando     de Abreu   5

In [10]:
player_pos[:5]

              player    position  Unnamed: 2  Unnamed: 3  Unnamed: 4
0         Almen Abdi  Midfielder         NaN         NaN         NaN
1      Tammy Abraham     Forward         NaN         NaN         NaN
2       Charlie Adam  Midfielder         NaN         NaN         NaN
3         Adam Smith    Defender         NaN         NaN         NaN
4  Emmanuel Adebayor     Forward         NaN         NaN         NaN

In [11]:
fname = player_id['first_name'][0]
sname = player_id['second_name'][0]
pname = fname + ' ' + sname
print pname

David Ospina

In [12]:
pname2 = player_pos['player'][0]
print pname2

Almen Abdi

In [13]:
n = 0
m = 0
for i in player_id.index:
    fname = player_id['first_name'][i]
    sname = player_id['second_name'][i]
    pname = fname + ' ' + sname
    n += 1
    for j in player_pos.index:
        if player_pos['player'][j] == pname:
#             print pname, player_pos['position'][j]
            m += 1
            player_id.loc[i, 'position'] = player_pos['position'][j]
# print n, m

In [14]:
player_id

          first_name         second_name   id    position
0              David              Ospina    1  Goalkeeper
1               Petr                Cech    2  Goalkeeper
2            Laurent           Koscielny    3    Defender
3                Per         Mertesacker    4    Defender
4    Gabriel Armando            de Abreu    5         NaN
5             Héctor            Bellerín    6         NaN
6             Kieran               Gibbs    7    Defender
7            Mathieu             Debuchy    8    Defender
8               Carl           Jenkinson    9    Defender
9              Nacho             Monreal   10    Defender
10             Calum            Chambers   11    Defender
11            Alexis             Sánchez   12         NaN
12              Theo             Walcott   13     Forward
13             Mesut                Özil   14         NaN
14          Santiago             Cazorla   15  Midfielder
15             Aaron              Ramsey   16  Midfielder
16              Jack            Wilshere   17  Midfielder
17              Alex  Oxlade-Chamberlain   18  Midfielder
18             Serge              Gnabry   19     Forward
19           Francis            Coquelin   20  Midfielder
20              Alex               Iwobi   21  Midfielder
21           Mohamed              Elneny   22  Midfielder
22              Joel            Campbell   23     Forward
23            Granit               Xhaka   24  Midfielder
24           Olivier              Giroud   25     Forward
25             Danny             Welbeck   26     Forward
26              Yaya              Sanogo   27     Forward
27            Takuma               Asano   28         NaN
28             Artur               Boruc   29  Goalkeeper
29              Adam            Federici   30  Goalkeeper
..               ...                 ...  ...         ...
653           Connor             Roberts  654         NaN
654          Matthew             Willock  655         NaN
655             Axel            Tuanzebe  656    Defender
656  Damian Emiliano            Martinez  657         NaN
657              Joe            Williams  658  Midfielder
658             Dion             Pereira  659  Midfielder
659             Matt               Macey  660  Goalkeeper
660            James             Husband  661    Defender
661       Joel Dinis      Castro Pereira  662         NaN
662          Eduardo   Dos Reis Carvalho  663         NaN
663            Moses              Makasi  664  Midfielder
664           Nathan             Holland  665         NaN
665            Rhian            Brewster  666         NaN
666            Scott           McTominay  667         NaN
667            Angus                Gunn  668  Goalkeeper
668          Demetri            Mitchell  669         NaN
669          Elliott               Moore  670         NaN
670            Filip             Lesniak  671         NaN
671           Samuel            Shashoua  672         NaN
672          Zachary            Dearnley  673         NaN
673           Joshua              Harrop  674         NaN
674           Daniel                Kemp  675  Midfielder
675           Daniel               Batty  676         NaN
676            Aaron            Ramsdale  677         NaN
677          Matthew         Worthington  678         NaN
678              Sam            Surridge  679     Forward
679            Angel               Gomes  680         NaN
680           Kieran              O'Hara  681         NaN
681          Gerhard             Tremmel  682         NaN
682             Rene           Gilmartin  683  Goalkeeper

[683 rows x 4 columns]

In [15]:
player_id.to_csv('player_position.csv')

In [20]:
import pandas as pd

schedule_16_17 = pd.read_csv('data/UK_Football_Fixtures_2016-17.csv', usecols=['HOME TEAM', 'AWAY TEAM'])
schedule_16_17['GAMEWEEK'] = [i / 10 + 1 for i in range(schedule_16_17.shape[0])]
schedule_16_17.set_index('GAMEWEEK', drop=True, inplace=True)

#print schedule_16_17

schedule_17_18 = pd.read_csv('data/UK_Football_Fixtures_2017-18.csv', usecols=['HOME TEAM', 'AWAY TEAM'])
schedule_17_18['GAMEWEEK'] = [i / 10 + 1 for i in range(schedule_17_18.shape[0])]
schedule_17_18.set_index('GAMEWEEK', drop=True, inplace=True)

print schedule_17_18.loc[1]

                       HOME TEAM          AWAY TEAM
GAMEWEEK
1                        Arsenal     Leicester City
1         Brighton & Hove Albion    Manchester City
1                        Chelsea            Burnley
1                 Crystal Palace  Huddersfield Town
1                        Everton         Stoke City
1              Manchester United    West Ham United
1               Newcastle United  Tottenham Hotspur
1                    Southampton       Swansea City
1                        Watford          Liverpool
1           West Bromwich Albion        Bournemouth

In [ ]:
#select data for attackers only
#find features describing those players
#train over those features... for complete 16-17 data and history...
#get some points for a player
#for predicting next 1 game, look in the gameweek schedule dataframe, and see the opponents
#for the opponent, look at the opponent's score / ranking etc..
#for the player, see whether next match is at home or away
#see player career wise score and current trend over last 5 games

#

In [49]:
non_player_features = ['opponent_team', 'was_home']

non_player_features_df = p_gwData[p_gwData['minutes']>0]

non_player_features_train_df = non_player_features_df.loc[:,non_player_features]
non_player_features_test_df = non_player_features_df.loc[:,'total_points']



print non_player_features_train_df.shape

(10474, 2)

In [ ]:
##create test set 2017-18